"""Explicit primary exports; implementation owners use canonical module paths."""

_EXPORT_GROUPS: dict[str, tuple[str, ...]] = {
    "pymhm.adaptivity.darcy": ("mark_dorfler",),
    "pymhm.adaptivity.metric": ("ResidualMeshSize", "remesh_freefem", "residual_mesh_size"),
    "pymhm.backends.forms": ("assemble_form", "assemble_pairing"),
    "pymhm.backends.spaces": ("NativeSpace", "bind_space", "create_native_mesh"),
    "pymhm.core.assembly": (
        "HybridProblem",
        "LocalLinearSolver",
        "SolverConfig",
        "assemble_hybrid",
        "solve_hybrid",
    ),
    "pymhm.core.condensation": (
        "condense_local",
        "local_condensation_matrix",
        "local_condensation_system",
        "local_response_from_solution",
    ),
    "pymhm.core.contracts": ("HybridSolution", "LocalAssembly", "LocalProblem", "LocalResponse"),
    "pymhm.core.contributions": ("assemble_hybrid_contributions", "local_global_contribution"),
    "pymhm.core.context": ("BoundProblem", "GlobalContext", "LocalContext", "bind_problem"),
    "pymhm.core.equations": (
        "Equation",
        "LinearForms",
        "FormCompiler",
        "LocalEquations",
        "CompiledLocalEquations",
        "columns",
        "rows",
        "compile_form",
        "compile_local_equations",
    ),
    "pymhm.core.moments": ("energy_reconstruction",),
    "pymhm.core.multiscale": (
        "MultiscaleProblem",
        "MultiscaleSystem",
        "MultiscaleSolution",
        "NestedEquations",
        "assemble",
        "solve",
        "solve_multiscale_system",
        "reconstruct_multiscale",
        "with_global_load",
        "leaf_moment",
        "with_global_equation",
    ),
    "pymhm.core.nested": (
        "NestedLocalProblem",
        "NestedSolution",
        "nest_hybrid_system",
        "nested_trace_map",
    ),
    "pymhm.core.offline": (
        "LocalFactorCache",
        "OfflineHybridSystem",
        "OfflineLocalProblem",
        "condense_cached",
    ),
    "pymhm.core.reconstruction": (
        "local_condensed_load",
        "reconstruct_local",
        "reconstruct_response",
    ),
    "pymhm.core.refinement": (
        "HybridRefinement",
        "HybridRefinementCase",
        "HybridRefinementLocal",
        "HybridRefinementStore",
        "HybridStreamRefinement",
        "refine_hybrid",
        "refine_hybrid_stream",
    ),
    "pymhm.core.subspaces": ("restrict_response",),
    "pymhm.core.spaces": (
        "BoundInterface",
        "InterfaceSpace",
        "MeshHierarchy",
        "TraceBinding",
        "bind_interface",
        "bind_local_equations",
        "validate_trace_binding",
    ),
    "pymhm.core.system": ("HybridSystem", "hybrid_mean_constraint", "solve_hybrid_system"),
    "pymhm.core.variational": ("GlobalForm", "LocalForm", "LocalProvider", "compile_local_forms"),
    "pymhm.execution.cpu": ("ExecutionConfig", "iter_local", "map_local"),
    "pymhm.execution.cuda": (
        "BatchedFactorization",
        "assemble_p1_batch",
        "condense_batched",
        "condense_multi_gpu",
    ),
    "pymhm.execution.mpi": ("DistributedHybridSolution", "solve_distributed"),
    "pymhm.fem.hdiv.bdm_family": ("BDMFamily",),
    "pymhm.fem.hdiv.family_3d": ("HDiv3DFamily",),
    "pymhm.fem.hdiv.rt": ("RTField",),
    "pymhm.fem.hdiv.rt_3d": ("RTTetraFamily",),
    "pymhm.fem.quadrature.material": (
        "cartesian_edge_quadrature",
        "cartesian_trace_values",
        "fit_material_faces",
        "fit_material_mesh",
        "material_triangle_quadrature",
    ),
    "pymhm.fem.quadrature.planar": ("planar_edge_quadrature", "planar_simplex_quadrature"),
    "pymhm.fem.reference": (
        "NodalReferenceBasis",
        "ReferenceElement",
        "ReferenceElementSpec",
        "barycentric_simplex_tabulation",
        "create_reference_element",
        "interpolate_reference",
        "legendre_tabulation",
        "legendre_values",
        "monomial_tabulation",
        "nodal_base_transformations",
        "orthogonal_polynomial_tabulation",
        "reference_base_transformations",
        "reference_entity_dofs",
        "reference_entity_transformations",
        "reference_interpolation_points",
        "simplex_lagrange_basis",
        "simplex_lagrange_tabulation",
        "tabulate_reference",
        "tensor_lagrange_basis",
        "tensor_lagrange_tabulation",
    ),
    "pymhm.fem.traces.helmholtz": (
        "OscillatoryFaceSpace",
        "PolynomialNeumannTrace",
        "helmholtz_skeleton",
    ),
    "pymhm.fem.traces.interval": ("FaceSpace", "SkeletonSpace", "interface_pairing"),
    "pymhm.fem.traces.pressure_3d": ("PressureTraceSpace3D",),
    "pymhm.fem.traces.triangle_3d": ("TriangularSkeleton",),
    "pymhm.fem.vector.curl": ("CurlOperators", "TangentialTraceSpace"),
    "pymhm.io.native": ("from_gmsh_3d", "from_netgen_3d"),
    "pymhm.io.tetrahedral": ("TetraMeshData", "read_tetra_mesh", "write_tetra_mesh"),
    "pymhm.io.volume": (
        "VolumeMeshData",
        "from_meshio",
        "read_volume_mesh",
        "to_meshio",
        "write_volume_mesh",
    ),
    "pymhm.linalg.block": ("SaddleBlockSolver",),
    "pymhm.linalg.dynamics": ("newmark_step",),
    "pymhm.linalg.moments": ("solve_moment_system",),
    "pymhm.linalg.separable": (
        "SeparableKrylovSolution",
        "TensorDiffusionOperator",
        "solve_separable_krylov",
        "tensor_diffusion_operator",
    ),
    "pymhm.materials.planar": ("PlanarMaterial", "PlanarRegion"),
    "pymhm.materials.sources": ("PolylineLayerField", "RadialDiskLoad"),
    "pymhm.meshes.cartesian": ("CartesianMacroMesh",),
    "pymhm.meshes.fitting": (
        "PlanarFittedMesh",
        "fit_planar_material",
        "fit_planar_skeleton",
        "planar_face_partitions",
    ),
    "pymhm.meshes.hexahedron": ("HexMesh",),
    "pymhm.meshes.longest_edge": ("refine_longest_edge",),
    "pymhm.meshes.mixed": ("AffineMixedMesh",),
    "pymhm.meshes.polygonal": ("PolygonMesh",),
    "pymhm.meshes.polyhedral": ("PolyhedralMesh",),
    "pymhm.meshes.refinement": (
        "TriangleRefinement",
        "refine_triangles",
        "transfer_skeleton",
        "validate_submesh",
    ),
    "pymhm.meshes.refinement_3d": ("TetraRefinement", "refine_tetrahedra"),
    "pymhm.meshes.tetrahedron": ("TetraMesh",),
    "pymhm.meshes.triangle": ("TriangleMesh",),
    "pymhm.methods.hho": ("MsHHOLocal", "MsHHOSolution"),
    "pymhm.methods.hho_3d": ("MsHHO3DSolution",),
    "pymhm.methods.petrov_galerkin": ("PGMHMSolution",),
    "pymhm.methods.robin": ("MHSolution",),
    "pymhm.methods.robin_3d": ("MH3DSolution",),
    "pymhm.methods.three_field": ("MH2MLocal", "MH2MSolution", "PressureTraceSpace"),
    "pymhm.methods.three_field_3d": ("MH2M3DSolution",),
    "pymhm.recovery.moments": (
        "MomentFluxSolution",
        "reconstruct_darcy_moments",
        "reconstruct_flux_moments",
    ),
    "pymhm.recovery.moments_3d": ("MomentFlux3DSolution", "reconstruct_darcy_moments_3d"),
    "pymhm.postprocessing.fields": (
        "DiscreteField",
        "FieldDefinition",
        "evaluate_field",
        "evaluate_field_and_gradient",
        "evaluate_field_gradient",
        "local_trace",
        "portable_field_coefficients",
        "solution_field",
    ),
}

PUBLIC_EXPORTS: dict[str, tuple[str, str]] = {
    name: (module, name) for module, names in _EXPORT_GROUPS.items() for name in names
}
PUBLIC_NAMES = sorted(PUBLIC_EXPORTS)
