"""Check generated mathematical markup before browser-side MathJax rendering.

The check detects unprotected TeX, damaged Markdown tables and display blocks
lost during conversion. It does not compile TeX or replace a browser rendering
check. Only the Python standard library is required.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, field
from html.parser import HTMLParser
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any

_IGNORED_TAGS = {"code", "pre", "script", "style", "textarea", "noscript", "title"}
_VOID_TAGS = {
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "link",
    "meta",
    "param",
    "source",
    "track",
    "wbr",
}
_RAW_TEX = re.compile(r"\\(?:[A-Za-z]+|[()[\]])|\$")
_FENCE = re.compile(r"^\s*(`{3,}|~{3,})")


@dataclass
class _Element:
    """Track HTML ancestry and the text of one protected mathematical expression."""

    tag: str
    line: int
    ignored: bool
    math: bool
    text: list[str] = field(default_factory=list)


class MathMarkupParser(HTMLParser):
    """Inspect raw HTML without treating code examples as rendered mathematics."""

    def __init__(self) -> None:
        """Initialize expression counts and line-numbered conversion diagnostics."""
        super().__init__(convert_charrefs=True)
        self.stack: list[_Element] = []
        self.inline_count = 0
        self.display_count = 0
        self.issues: list[tuple[int, str]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        """Track protected expressions and reject Markdown elements inside them."""
        attributes = dict(attrs)
        ignored = tag in _IGNORED_TAGS or any(item.ignored for item in self.stack)
        math = not ignored and "arithmatex" in (attributes.get("class") or "").split()
        if not ignored and any(item.math for item in self.stack):
            self.issues.append((self.getpos()[0], f"HTML element <{tag}> inside TeX markup"))
        if math:
            if tag == "div":
                self.display_count += 1
            elif tag == "span":
                self.inline_count += 1
            else:
                self.issues.append((self.getpos()[0], f"Unexpected <{tag}> arithmatex wrapper"))
        if tag not in _VOID_TAGS:
            self.stack.append(_Element(tag, self.getpos()[0], ignored, math))

    def handle_endtag(self, tag: str) -> None:
        """Validate each mathematical wrapper when its closing tag is encountered."""
        for index in range(len(self.stack) - 1, -1, -1):
            if self.stack[index].tag == tag:
                for element in self.stack[index:]:
                    if element.math:
                        text = "".join(element.text).strip()
                        opening, closing = (
                            (r"\[", r"\]") if element.tag == "div" else (r"\(", r"\)")
                        )
                        if not (text.startswith(opening) and text.endswith(closing)):
                            self.issues.append((element.line, "Incomplete arithmatex delimiters"))
                del self.stack[index:]
                return

    def handle_data(self, data: str) -> None:
        """Locate TeX outside protected wrappers, retaining text for wrapper checks."""
        if any(item.ignored for item in self.stack):
            return
        protected = [item for item in self.stack if item.math]
        if protected:
            for element in protected:
                element.text.append(data)
        elif _RAW_TEX.search(data):
            snippet = " ".join(data.split())[:160]
            self.issues.append(
                (self.getpos()[0], f"Unprotected TeX or dollar delimiter: {snippet}")
            )

    def finish(self) -> None:
        """Finish parsing and diagnose unclosed mathematical HTML wrappers."""
        self.close()
        for element in self.stack:
            if element.math:
                self.issues.append((element.line, "Unclosed arithmatex wrapper"))


def source_display_count(source: str) -> tuple[int, list[tuple[int, str]]]:
    r"""Count Markdown displays delimited by ``$$`` or ``\[`` outside code fences.

    These are source blocks, not docstrings generated by mkdocstrings. Inline
    code and indented code outside a display do not contribute to the count.
    """
    count = 0
    fence = ""
    closing = ""
    opening_line = 0
    issues: list[tuple[int, str]] = []
    for number, line in enumerate(source.splitlines(), 1):
        match = _FENCE.match(line)
        if match and not closing:
            delimiter = match.group(1)
            if not fence:
                fence = delimiter
            elif delimiter[0] == fence[0] and len(delimiter) >= len(fence):
                fence = ""
            continue
        if fence:
            continue
        text = line.strip()
        if closing:
            if text.endswith(closing):
                closing = ""
            continue
        if line.startswith(("    ", "\t")):
            continue
        for opening, end in (("$$", "$$"), (r"\[", r"\]")):
            if text.startswith(opening):
                count += 1
                remainder = text[len(opening) :]
                if not remainder.endswith(end):
                    closing = end
                    opening_line = number
                break
        else:
            if text == r"\]":
                issues.append((number, "Display closing delimiter without an opening"))
    if closing:
        issues.append((opening_line, "Unclosed mathematical display in Markdown"))
    return count, issues


def audit_site(
    site_dir: Path, docs_dir: Path, excluded_sources: set[Path] | None = None
) -> tuple[int, int, list[str]]:
    """Check all source TeX and every HTML page in the selected publication profile.

    Excluded supplementary sources retain Markdown delimiter checks but do not
    require generated HTML. No generated mathematical expression is skipped.
    """
    html_files = sorted(site_dir.rglob("*.html"))
    if not html_files:
        raise ValueError(f"No generated HTML files found in {site_dir}")
    markdown_files = sorted(docs_dir.rglob("*.md"))
    if not markdown_files:
        raise ValueError(f"No Markdown source files found in {docs_dir}")
    issues: list[str] = []
    parsed: dict[Path, MathMarkupParser] = {}
    for path in html_files:
        parser = MathMarkupParser()
        parser.feed(path.read_text(encoding="utf-8"))
        parser.finish()
        parsed[path] = parser
        issues.extend(f"{path}:{line}: {message}" for line, message in parser.issues)
    for source_path in markdown_files:
        source = source_path.read_text(encoding="utf-8")
        expected, source_issues = source_display_count(source)
        issues.extend(f"{source_path}:{line}: {message}" for line, message in source_issues)
        relative = source_path.relative_to(docs_dir)
        page = site_dir / relative.with_suffix(".html")
        if relative.name != "index.md":
            directory_page = site_dir / relative.with_suffix("") / "index.html"
            if directory_page in parsed:
                page = directory_page
        if page not in parsed:
            if relative not in (excluded_sources or set()):
                issues.append(f"{source_path}: Generated HTML page is missing")
        elif not re.search(r"^\s*:::\s+", source, re.MULTILINE):
            actual = parsed[page].display_count
            if actual != expected:
                issues.append(
                    f"{source_path}: {expected} Markdown display blocks but "
                    f"{actual} protected HTML displays in {page}"
                )
    total = sum(parser.inline_count + parser.display_count for parser in parsed.values())
    return len(html_files), total, issues


def _profile_paths(entries: Any, docs_dir: Path, field_name: str) -> set[Path]:
    """Validate existing checkout-relative Markdown paths in a publication profile."""
    if not isinstance(entries, list):
        raise ValueError(f"Publication profile {field_name} must be a list")
    result: set[Path] = set()
    for entry in entries:
        if not isinstance(entry, str) or not entry or entry != entry.strip():
            raise ValueError(f"Invalid Markdown source in publication profile: {entry!r}")
        path = Path(entry)
        if (
            PurePosixPath(entry).is_absolute()
            or PureWindowsPath(entry).drive
            or ".." in path.parts
            or "\\" in entry
            or any(ord(character) < 32 for character in entry)
            or path.suffix != ".md"
        ):
            raise ValueError(f"Invalid Markdown source in publication profile: {entry}")
        candidate = docs_dir / path
        if not candidate.resolve().is_relative_to(docs_dir.resolve()) or not candidate.is_file():
            raise ValueError(f"Publication profile source is missing or outside docs: {entry}")
        if path in result:
            raise ValueError(f"Duplicate Markdown source in publication profile: {entry}")
        result.add(path)
    return result


def excluded_markdown_sources(docs_dir: Path) -> set[Path]:
    """Read an optional profile without permitting malformed or canonical exclusions.

    An exclusion changes only the requirement for a matching generated page.
    ``audit_site`` still checks every source and every HTML expression.
    """
    manifest = docs_dir / "publication-core.json"
    if not manifest.exists():
        return set()
    try:
        profile = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise ValueError("Cannot read the documentation publication profile") from error
    if (
        not isinstance(profile, dict)
        or type(profile.get("schema_version")) is not int
        or profile["schema_version"] != 1
    ):
        raise ValueError("Documentation publication profile must use schema_version 1")
    excluded = _profile_paths(profile.get("excluded_pages"), docs_dir, "excluded_pages")
    canonical = _profile_paths(profile.get("canonical_pages", []), docs_dir, "canonical_pages")
    if excluded & canonical:
        raise ValueError("Canonical Markdown sources cannot be excluded from publication")
    return excluded


def main() -> None:
    """Fail the documentation gate when generated mathematical markup is damaged."""
    arguments = argparse.ArgumentParser(description=__doc__)
    arguments.add_argument("--site-dir", type=Path, default=Path("site"))
    arguments.add_argument("--docs-dir", type=Path, default=Path("docs"))
    args = arguments.parse_args()
    try:
        excluded = excluded_markdown_sources(args.docs_dir)
        pages, expressions, issues = audit_site(args.site_dir, args.docs_dir, excluded)
    except ValueError as error:
        raise SystemExit(str(error)) from error
    if issues:
        raise SystemExit("Mathematical markup validation failed:\n" + "\n".join(issues))
    print(f"Validated mathematical markup: {pages} HTML pages, {expressions} expressions")


if __name__ == "__main__":
    main()
