"""Inventory and validate locally generated field archives read by scientific notebooks.

Selectors mirror the notebook code, including checksum-only reads. The lightweight
Git checkout contains records and sources; field payloads are generated by their
corresponding public calculations.
This helper never downloads data or changes scientific checksum checks.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

DEFAULT_MAX_BYTES = 3 * 1024**3
PLACEHOLDER_HEADER = b"version https://git-lfs.github.com/spec/v1\n"


def required_archives(root: Path) -> dict[str, set[Path]]:
    """Return notebook identifiers and actual field-byte dependencies from their JSON selectors."""
    base = root / "examples/results"
    found: dict[str, set[Path]] = {}

    def read(path: Path) -> Any:
        """Read a versioned scientific record without opening its field arrays."""
        return json.loads(path.read_text(encoding="utf-8"))

    def add(notebook: str, path: Path) -> None:
        """Keep exact file dependencies grouped by their consuming notebook."""
        found.setdefault(notebook, set()).add(path)

    def rows(
        notebook: str, folder: Path, sequence: list[dict[str, Any]], key: str = "archive"
    ) -> None:
        """Collect a field name from each selected scientific result."""
        for row in sequence:
            if key in row:
                add(notebook, folder / row[key])

    rows("14", base / "neopz", read(base / "neopz/comparison.json")["rows"])
    rows("15", base, read(base / "elasticity-reference.json")["rows"])
    report = read(base / "native-extensions/report.json")
    for name in ("darcy", "flow", "rad", "layer", "heat"):
        for row in report[name]:
            if "fields" in row:
                add("19", base / "native-extensions" / row["fields"]["file"])
    add("21", base / "spe10/layer-36.npz")
    folder = base / "quarter-five-spot/reference"
    report = read(folder / "classical-convergence.json")
    rows("22", folder, read(folder / "comparison.json")["cases"], "fields")
    rows("22", folder, report["levels"] + report["mhm_trace_enrichment"], "fields")
    folder = base / "spe10"
    for path in folder.glob("darcy-q1-r*-s32.json"):
        row = read(path)
        if row["coefficient_pixels_aligned"]:
            add("23", folder / row["archive"])
    add("23", folder / read(folder / "reference-q3-768x1408-order5.json")["archive"])
    report = read(folder / "darcy-flux-comparison.json")
    rows("23", folder, [report["mhm"], *report["references"].values()])
    add(
        "23",
        folder / read(folder / "flow-layer1-n6x11-p3-r10-s10-q5-pointwise-2017.json")["archive"],
    )
    th = sorted(
        [read(path) for path in folder.glob("taylor-hood-[0-9]*x[0-9]*.json")],
        key=lambda row: row["unknowns"],
    )
    rows("23", folder, th)
    add("23", folder / "layer-1.npz")
    nx, ny = th[-1]["mesh_shape"]
    add("23", folder / read(folder / f"taylor-hood-mhm-{nx}x{ny}.json")["mhm"])
    for notebook, name in [("33", "darcy-rt"), ("41", "rad3d")]:
        add(notebook, base / read(base / f"{name}.json")["rows"][-1]["fields"])
    folder = base / "unfitted/convergence/msl-smooth"
    rows("38", folder, read(folder / "comparison.json")["rows"])
    folder = base / "unfitted/convergence"
    for name in read(folder / "comparison.json")["acquisition_sha256"]:
        rows("38", folder, read(folder / name)["cases"])
    rows("38", folder, read(folder / "smooth-p8-r64-endpoints.json")["cases"])
    folder = base / "mixed-well-geometries"
    rows("51", folder, [read(path) for path in folder.glob("*-fine*-macro*.json")])
    folder = base / "unusual"
    for name in ("analytical", "resolution-control"):
        rows("53", folder, read(folder / f"{name}.json")["rows"])
    folder = base / "unusual-spe10"
    add("53", folder / read(folder / "classical-cg2-graded-xy-1440x498.json")["archive"])
    for path in folder.glob("mhm-unusual-*-comparison.json"):
        row = read(path)
        if len(row["rows"]) == 2:
            add("53", folder / row["archive"])
    for notebook, name in [("54", "flow3d"), ("55", "gals3d"), ("63", "planar3d")]:
        folder = base / name
        rows(notebook, folder, read(folder / "campaign.json")["rows"], "fields")
    folder = base / "pgmhm-inclusions"
    for path in [
        *folder.glob("classical-cg2-*.json"),
        *folder.glob("mhm-pgmhm-*-comparison.json"),
        *(base / "pgmhm-spe10/kx").rglob("*-comparison.json"),
    ]:
        row = read(path)
        for name in ("archive", "reference", "mhm"):
            if name in row and name + "_sha256" in row:
                add("59", record_archive(path, row[name]))
    folder = base / "tetra-pk"
    recovered = read(folder / "reconstruction-order.json")
    rows(
        "64",
        folder,
        read(folder / "uniform.json")["rows"] + read(folder / "fixed.json")["rows"] + [recovered],
    )
    add("64", folder / recovered["parent_archive"])
    folder = base / "maxwell-nanoguide"
    report = read(folder / "comparison.json")
    controls = read(folder / "refinement-controls.json")
    for row in [*report["comparisons"], *controls.values()]:
        for name in ("field", "reference"):
            add("66", folder / row[name]["file"])
    folder = base / "star-polyhedra"
    rows("67", folder, read(folder / "comparison.json")["rows"])
    folder = base / "mixed-elasticity3d"
    rows("68", folder, read(folder / "comparison.json")["convergence"])
    folder = base / "mh2m-heterogeneous/crisscross"
    rows("70", folder, read(folder / "comparison.json")["cases"])
    folder = base / "mh2m-heterogeneous/cg3"
    report = read(folder / "comparison.json")
    rows(
        "70",
        folder,
        report["reference_acquisitions"] + [report["assembly_quadrature_control"]["acquisition"]],
    )
    folder = base / "elastodynamics"
    for name in read(folder / "comparison.json")["field_sha256"]:
        add("71", folder / name)
    folder = base / "marmousi"
    rows("72", folder, read(folder / "classical-convergence.json")["references"], "sample_archive")
    add("72", folder / read(folder / "mhm-H20-ell1.json")["archive"])
    return found


def record_archive(record: Path, name: str) -> Path:
    """Locate an archive using versioned records, independent of payload presence."""
    own = record.parent / name
    parent = record.parent.parent / name
    if not own.with_suffix(".json").is_file() and parent.with_suffix(".json").is_file():
        return parent
    return own


def archive_size(path: Path) -> int:
    """Count local payload bytes, rejecting legacy placeholders without loading arrays."""
    with path.open("rb") as stream:
        header = stream.read(len(PLACEHOLDER_HEADER))
    if header.startswith(PLACEHOLDER_HEADER):
        raise ValueError(f"External field archive is a placeholder, not a payload: {path.name}")
    return path.stat().st_size


def dependency_plan(root: Path, dependencies: dict[str, set[Path]]) -> dict[str, Any]:
    """List exact field paths and missing payloads before their calculation."""
    root = root.resolve()
    result: dict[str, Any] = {"notebooks": {}, "archives": {}, "payload_bytes": 0, "missing": []}
    for notebook, paths in sorted(dependencies.items()):
        names = []
        for path in sorted(paths):
            relative = path.resolve().relative_to(root).as_posix()
            if (
                not relative.startswith("examples/results/")
                or path.suffix not in {".npz", ".vtu"}
                or any(character in relative for character in ",*?[]\\\n\r")
            ):
                raise ValueError(f"Unsafe or unsupported archive path: {relative}")
            names.append(relative)
            if relative not in result["archives"]:
                available = path.is_file()
                size = archive_size(path) if available else None
                result["archives"][relative] = {"bytes": size, "available": available}
                if size is None:
                    result["missing"].append(relative)
                else:
                    result["payload_bytes"] += size
        result["notebooks"][notebook] = names
    result["archive_count"] = len(result["archives"])
    return result


def validate_archives(root: Path, plan: dict[str, Any], maximum_bytes: int) -> None:
    """Require generated local files within an explicit budget before notebook execution."""
    if maximum_bytes < 1:
        raise ValueError("The notebook archive budget must be positive")
    missing = [name for name in plan["archives"] if not (root / name).is_file()]
    if missing:
        sample = ", ".join(missing[:5])
        raise ValueError(
            f"Missing {len(missing)} computed notebook field archive(s): {sample}. "
            "Generate the corresponding public cases described in the documentation "
            "and CONTINUATION.md. No automatic result download is configured."
        )
    total = sum(archive_size(root / name) for name in plan["archives"])
    if total > maximum_bytes:
        raise ValueError(
            f"Notebook archives require {total:,} bytes, exceeding "
            f"the explicit {maximum_bytes:,}-byte budget"
        )


def main() -> None:
    """List dependencies by default; validate generated payloads when requested."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Require the selected local payloads")
    parser.add_argument("--max-bytes", type=int, default=DEFAULT_MAX_BYTES)
    parser.add_argument("--notebook", action="append", help="Select an ID, for example 23 or 47")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    dependencies = required_archives(root)
    if args.notebook:
        available = {path.name.split("_", 1)[0] for path in (root / "notebooks").glob("*.ipynb")}
        if set(args.notebook) - available:
            parser.error("Unknown notebook identifier")
        dependencies = {key: value for key, value in dependencies.items() if key in args.notebook}
    plan = dependency_plan(root, dependencies)
    print(json.dumps(plan, indent=2), flush=True)
    if args.check:
        try:
            validate_archives(root, plan, args.max_bytes)
        except ValueError as error:
            parser.error(str(error))


if __name__ == "__main__":
    main()
