"""Inventory and validate locally generated field archives read by scientific notebooks.

Selectors mirror the notebook code, including checksum-only reads. Downloaded
sources declare their resource identities; field payloads are acquired or
generated by their corresponding public calculations.
The notebook runner prepares missing inputs through declared public producers;
this inventory helper does not change scientific checksum checks.
"""

from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path, PurePosixPath
from typing import Any

from pymhm.io.workspace import case_workspace, local_resource, resource_glob

DEFAULT_MAX_BYTES = 3 * 1024**3
PLACEHOLDER_HEADER = b"version https://git-lfs.github.com/spec/v1\n"
IMAGE_MANIFEST = Path(__file__).with_name("notebook_images.json")


def notebook_identifier(path: Path) -> str:
    """Return a historical numeric prefix, or the stem of an unnumbered tutorial.

    Moving a notebook between problem folders does not change its data contract.
    A new tutorial need not reserve a numeric identifier.
    """
    prefix = path.stem.split("_", 1)[0]
    return prefix if prefix.isdecimal() else path.stem


def discover_notebooks(root: Path) -> list[Path]:
    """Find notebook sources recursively, excluding Jupyter checkpoint copies.

    Historical numeric identifiers must remain unique across problem folders.
    Notebook sources discovered inside the checkout cannot point outside it.
    """
    base = (root / "notebooks").resolve()
    notebooks = []
    numbered: dict[str, Path] = {}
    for path in sorted(base.rglob("*.ipynb")):
        if ".ipynb_checkpoints" in path.relative_to(base).parts or not path.is_file():
            continue
        if not path.resolve().is_relative_to(base):
            raise ValueError(f"Notebook source escapes the notebook directory: {path}")
        identifier = notebook_identifier(path)
        if identifier.isdecimal():
            if identifier in numbered:
                raise ValueError(
                    f"Duplicate notebook identifier {identifier}: "
                    f"{numbered[identifier].relative_to(base)} and {path.relative_to(base)}"
                )
            numbered[identifier] = path
        notebooks.append(path)
    return notebooks


def select_notebooks(
    root: Path, selectors: list[str] | None = None, *, allow_external: bool = False
) -> list[Path]:
    """Select sources by identifier, path, filename or problem folder.

    Folder selection includes its descendants; repeated selections execute a
    source once. Ambiguous basenames require a qualified path. Existing external
    ``.ipynb`` files are accepted only when explicitly enabled by the runner.
    """
    base = (root / "notebooks").resolve()
    available = discover_notebooks(root)
    if not selectors:
        return available
    selected: set[Path] = set()
    for selector in selectors:
        name = Path(selector).as_posix().removeprefix("./").rstrip("/")
        matches = []
        for path in available:
            relative = path.relative_to(base).as_posix()
            if name in {
                notebook_identifier(path),
                path.name,
                path.stem,
                relative,
                f"notebooks/{relative}",
                path.as_posix(),
            }:
                matches.append(path)
        if len(matches) > 1:
            raise ValueError(f"Ambiguous notebook selector {selector!r}; use a qualified path")
        if not matches:
            group = name.removeprefix("notebooks/")
            matches = [
                path
                for path in available
                if name == "notebooks"
                or group in {parent.as_posix() for parent in path.relative_to(base).parents}
            ]
        if not matches and allow_external:
            candidate = Path(selector).expanduser().resolve()
            if candidate.is_file() and candidate.suffix == ".ipynb":
                matches = [candidate]
        if not matches:
            raise ValueError(f"Unknown notebook identifier, path or problem group: {selector}")
        selected.update(matches)
    return sorted(selected)


def selected_notebook_ids(root: Path, notebooks: list[Path]) -> set[str]:
    """Select declared identities, including downloaded notebook sources.

    An unrelated external source does not inherit a contract from its basename.
    Its literal ``notebook_workspace`` declaration is required instead.
    """
    return {
        notebook_identifier(Path(selector))
        for path in notebooks
        if (selector := notebook_selector(root, path)) is not None
    }


def notebook_selector(root: Path, source: Path) -> str | None:
    """Identify a source's catalogue path without executing any notebook code.

    Sources inside ``root/notebooks`` use their literal relative path. External
    downloaded sources may declare one literal ``notebook_workspace(selector)``
    call imported from ``scripts.notebook_reproduction``. Aliases are accepted, dynamic
    expressions are not evaluated, and conflicting or escaping paths are rejected.
    """
    base = (root / "notebooks").resolve()
    if source.resolve().is_relative_to(base):
        return source.resolve().relative_to(base).as_posix()
    notebook = json.loads(source.read_text(encoding="utf-8"))
    functions: set[str] = set()
    modules: set[str] = set()
    trees = []
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        value = cell.get("source", "")
        text = "".join(value) if isinstance(value, list) else value
        text = "\n".join(
            "" if line.lstrip().startswith(("%", "!")) else line for line in text.splitlines()
        )
        try:
            tree = ast.parse(text)
        except SyntaxError:
            continue
        trees.append(tree)
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module in {
                "scripts.notebook_reproduction",
                "pymhm.io.workspace",
            }:
                functions.update(
                    alias.asname or alias.name
                    for alias in node.names
                    if alias.name == "notebook_workspace"
                )
            elif isinstance(node, ast.Import):
                modules.update(
                    alias.asname or alias.name
                    for alias in node.names
                    if alias.name in {"scripts.notebook_reproduction", "pymhm.io.workspace"}
                )
    selectors: set[str] = set()
    for tree in trees:
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            name = ast.unparse(node.func)
            if name not in functions and name not in {
                f"{module}.notebook_workspace" for module in modules
            }:
                continue
            argument = (
                node.args[0]
                if node.args
                else next(
                    (keyword.value for keyword in node.keywords if keyword.arg == "selector"), None
                )
            )
            if not isinstance(argument, ast.Constant) or not isinstance(argument.value, str):
                continue
            selector = argument.value.removeprefix("notebooks/")
            path = PurePosixPath(selector)
            if (
                not selector
                or path.is_absolute()
                or ".." in path.parts
                or "\\" in selector
                or path.suffix != ".ipynb"
            ):
                raise ValueError(f"Invalid notebook workspace selector: {argument.value!r}")
            selectors.add(path.as_posix())
    if len(selectors) > 1:
        raise ValueError(f"Conflicting notebook workspace selectors in {source}")
    return next(iter(selectors), None)


def required_images(root: Path, notebooks: set[str] | None = None) -> dict[str, set[Path]]:
    """Return existing notebook image contracts before any notebook is executed.

    Paths are external inputs displayed through ``Image``/``SVG``, excluding
    images produced earlier in that notebook. Adaptive mesh pages follow the
    selected campaign's number of records. Selection precedes campaign reads.
    """
    catalog = json.loads(IMAGE_MANIFEST.read_text(encoding="utf-8"))["notebooks"]
    result = {
        notebook: {root / name for name in names}
        for notebook, names in catalog.items()
        if notebooks is None or notebook in notebooks
    }
    if notebooks is None or "40" in notebooks:
        rows = json.loads(
            local_resource(
                root / "examples/results/spe10-adaptive/published/adaptive.json", root=root
            ).read_text(encoding="utf-8")
        )
        for page in range((len(rows) + 3) // 4):
            name = "meshes" if page == 0 else f"meshes-{page + 1}"
            result.setdefault("40", set()).add(root / f"docs/figures/spe10-adaptive/{name}.png")
    convergence = root / "examples/results/minimal-convergence/catalogue.json"
    if (notebooks is not None and "73" in notebooks) or (
        notebooks is None and convergence.is_file()
    ):
        for entry in json.loads(local_resource(convergence, root=root).read_text(encoding="utf-8"))[
            "entries"
        ]:
            result.setdefault("73", set()).add(root / entry["figure"])
    return result


def required_archives(root: Path, notebooks: set[str] | None = None) -> dict[str, set[Path]]:
    """Return field dependencies, reading manifests only for selected notebook IDs.

    ``None`` selects every notebook; an empty set selects none. Missing selected
    manifests still raise ``FileNotFoundError``. Field hashes remain checked by
    the scientific notebooks when they consume the generated payloads.
    """
    base = root / "examples/results"
    found: dict[str, set[Path]] = {}

    def selected(notebook: str) -> bool:
        """Select a family before reading any of its scientific records."""
        return notebooks is None or notebook in notebooks

    def read(path: Path) -> Any:
        """Read a versioned scientific record without opening its field arrays."""
        return json.loads(local_resource(path, root=root).read_text(encoding="utf-8"))

    def add(notebook: str, path: Path) -> None:
        """Keep exact file dependencies grouped by their consuming notebook."""
        found.setdefault(notebook, set()).add(path)

    def rows(
        notebook: str, folder: Path, sequence: list[dict[str, Any]], key: str = "archive"
    ) -> None:
        """Collect a field name from each selected scientific result."""
        for row in sequence:
            if key in row:
                add(notebook, folder / row[key])

    if selected("14"):
        rows("14", base / "neopz", read(base / "neopz/comparison.json")["rows"])
    if selected("15"):
        rows("15", base, read(base / "elasticity-reference.json")["rows"])
    if selected("19"):
        report = read(base / "native-extensions/report.json")
        for name in ("darcy", "flow", "rad", "layer", "heat"):
            for row in report[name]:
                if "fields" in row:
                    add("19", base / "native-extensions" / row["fields"]["file"])
    if selected("21"):
        add("21", base / "spe10/layer-36.npz")
    if selected("22"):
        folder = base / "quarter-five-spot/reference"
        report = read(folder / "classical-convergence.json")
        rows("22", folder, read(folder / "comparison.json")["cases"], "fields")
        rows("22", folder, report["levels"] + report["mhm_trace_enrichment"], "fields")
        point = base / "quarter-five-spot"
        rows("22", point, read(point / "point-wells.json")["rows"], "field_archive")
        rows("22", point, read(point / "point-convergence.json")["rows"])
    if selected("23"):
        folder = base / "spe10"
        for path in resource_glob(folder, "darcy-q1-r*-s32.json", root=root):
            row = read(path)
            if row["coefficient_pixels_aligned"]:
                add("23", folder / row["archive"])
        add("23", folder / read(folder / "reference-q3-768x1408-order5.json")["archive"])
        report = read(folder / "darcy-flux-comparison.json")
        rows("23", folder, [report["mhm"], *report["references"].values()])
        add(
            "23",
            folder
            / read(folder / "flow-layer1-n6x11-p3-r10-s10-q5-pointwise-2017.json")["archive"],
        )
        th = sorted(
            [
                read(path)
                for path in resource_glob(folder, "taylor-hood-[0-9]*x[0-9]*.json", root=root)
            ],
            key=lambda row: row["unknowns"],
        )
        rows("23", folder, th)
        add("23", folder / "layer-1.npz")
        nx, ny = th[-1]["mesh_shape"]
        add("23", folder / read(folder / f"taylor-hood-mhm-{nx}x{ny}.json")["mhm"])
    for notebook, name in [("33", "darcy-rt"), ("41", "rad3d")]:
        if selected(notebook):
            add(notebook, base / read(base / f"{name}.json")["rows"][-1]["fields"])
    if selected("36"):
        # The notebook replays only the explicitly selected one-sided field;
        # numerical archive validation remains in the scientific reader.
        add("36", base / read(base / "nested.json")["display_field"]["archive"])
    if selected("38"):
        folder = base / "unfitted/convergence/msl-smooth"
        rows("38", folder, read(folder / "comparison.json")["rows"])
        folder = base / "unfitted/convergence"
        for name in read(folder / "comparison.json")["acquisition_sha256"]:
            rows("38", folder, read(folder / name)["cases"])
        rows("38", folder, read(folder / "smooth-p8-r64-endpoints.json")["cases"])
    if selected("45"):
        folder = base / "rad-native"
        rows(
            "45",
            folder,
            [
                row
                for row in read(folder / "verification.json")["rows"]
                if row["kind"] == "conditioning"
            ],
        )
    if selected("51"):
        folder = base / "mixed-well-geometries"
        rows(
            "51",
            folder,
            [read(path) for path in resource_glob(folder, "*-fine*-macro*.json", root=root)],
        )
    if selected("53"):
        folder = base / "unusual"
        for name in ("analytical", "resolution-control"):
            rows("53", folder, read(folder / f"{name}.json")["rows"])
        folder = base / "unusual-spe10"
        add("53", folder / read(folder / "classical-cg2-graded-xy-1440x498.json")["archive"])
        for path in resource_glob(folder, "mhm-unusual-*-comparison.json", root=root):
            row = read(path)
            if len(row["rows"]) == 2:
                add("53", folder / row["archive"])
    for notebook, name in [("54", "flow3d"), ("55", "gals3d"), ("63", "planar3d")]:
        if selected(notebook):
            folder = base / name
            rows(notebook, folder, read(folder / "campaign.json")["rows"], "fields")
    if selected("59"):
        folder = base / "pgmhm-inclusions"
        for path in [
            *resource_glob(folder, "classical-cg2-*.json", root=root),
            *resource_glob(folder, "mhm-pgmhm-*-comparison.json", root=root),
            *resource_glob(base / "pgmhm-spe10/kx", "*-comparison.json", recursive=True, root=root),
        ]:
            row = read(path)
            for name in ("archive", "reference", "mhm"):
                if name in row and name + "_sha256" in row:
                    add("59", record_archive(path, row[name]))
    if selected("64"):
        folder = base / "tetra-pk"
        recovered = read(folder / "reconstruction-order.json")
        rows(
            "64",
            folder,
            read(folder / "uniform.json")["rows"]
            + read(folder / "fixed.json")["rows"]
            + [recovered],
        )
        add("64", folder / recovered["parent_archive"])
        previous = base / "reconstruction3d"
        rows("64", previous, read(previous / "resolution.json")["rows"])
    if selected("66"):
        folder = base / "maxwell-nanoguide"
        report = read(folder / "comparison.json")
        controls = read(folder / "refinement-controls.json")
        for row in [*report["comparisons"], *controls.values()]:
            for name in ("field", "reference"):
                add("66", folder / row[name]["file"])
    if selected("67"):
        folder = base / "star-polyhedra"
        rows("67", folder, read(folder / "comparison.json")["rows"])
    if selected("68"):
        folder = base / "mixed-elasticity3d"
        rows("68", folder, read(folder / "comparison.json")["convergence"])
    if selected("70"):
        folder = base / "mh2m-heterogeneous/crisscross"
        rows("70", folder, read(folder / "comparison.json")["cases"])
        folder = base / "mh2m-heterogeneous/cg3"
        report = read(folder / "comparison.json")
        rows(
            "70",
            folder,
            report["reference_acquisitions"]
            + [report["assembly_quadrature_control"]["acquisition"]],
        )
    if selected("71"):
        folder = base / "elastodynamics"
        for name in read(folder / "comparison.json")["field_sha256"]:
            add("71", folder / name)
    if selected("72"):
        folder = base / "marmousi"
        rows(
            "72",
            folder,
            read(folder / "classical-convergence.json")["references"],
            "sample_archive",
        )
        add("72", folder / read(folder / "mhm-H20-ell1.json")["archive"])
    return found


def record_archive(record: Path, name: str) -> Path:
    """Locate an archive using versioned records, independent of payload presence."""
    own = record.parent / name
    parent = record.parent.parent / name
    if not own.with_suffix(".json").is_file() and parent.with_suffix(".json").is_file():
        return parent
    return own


def archive_size(path: Path) -> int:
    """Count local payload bytes, rejecting legacy placeholders without loading arrays."""
    with path.open("rb") as stream:
        header = stream.read(len(PLACEHOLDER_HEADER))
    if header.startswith(PLACEHOLDER_HEADER):
        raise ValueError(f"External field archive is a placeholder, not a payload: {path.name}")
    return path.stat().st_size


def dependency_plan(
    root: Path,
    dependencies: dict[str, set[Path]],
    images: dict[str, set[Path]] | None = None,
) -> dict[str, Any]:
    """List exact field paths and missing payloads before their calculation."""
    root = root.resolve()
    result: dict[str, Any] = {"notebooks": {}, "archives": {}, "payload_bytes": 0, "missing": []}
    for notebook, paths in sorted(dependencies.items()):
        names = []
        for path in sorted(paths):
            relative = path.resolve().relative_to(root).as_posix()
            if (
                not relative.startswith("examples/results/")
                or path.suffix not in {".npz", ".vtu"}
                or any(character in relative for character in ",*?[]\\\n\r")
            ):
                raise ValueError(f"Unsafe or unsupported archive path: {relative}")
            names.append(relative)
            if relative not in result["archives"]:
                available = path.is_file()
                size = archive_size(path) if available else None
                result["archives"][relative] = {"bytes": size, "available": available}
                if size is None:
                    result["missing"].append(relative)
                else:
                    result["payload_bytes"] += size
        result["notebooks"][notebook] = names
    result["archive_count"] = len(result["archives"])
    result.update(notebook_images={}, images={}, image_bytes=0, missing_images=[])
    for notebook, paths in sorted((images or {}).items()):
        names = []
        for path in sorted(paths):
            relative = path.resolve().relative_to(root).as_posix()
            if (
                not relative.startswith("docs/figures/")
                or path.suffix.lower() not in {".png", ".jpg", ".jpeg", ".svg", ".pdf"}
                or any(character in relative for character in ",*?[]\\\n\r")
            ):
                raise ValueError(f"Unsafe or unsupported notebook image path: {relative}")
            names.append(relative)
            if relative not in result["images"]:
                available = path.is_file()
                size = archive_size(path) if available else None
                result["images"][relative] = {"bytes": size, "available": available}
                if size is None:
                    result["missing_images"].append(relative)
                else:
                    result["image_bytes"] += size
        result["notebook_images"][notebook] = names
    result["image_count"] = len(result["images"])
    return result


def validate_archives(root: Path, plan: dict[str, Any], maximum_bytes: int) -> None:
    """Require generated local files within an explicit budget before notebook execution."""
    if maximum_bytes < 1:
        raise ValueError("The notebook archive budget must be positive")
    missing = [name for name in plan["archives"] if not (root / name).is_file()]
    if missing:
        sample = ", ".join(missing[:5])
        raise ValueError(
            f"Missing {len(missing)} computed notebook field archive(s): {sample}. "
            "Generate the corresponding public cases with the declared recipes: "
            "python -m scripts.run_notebooks <selector> --plan. "
            "Omit --no-prepare to prepare the selected reproducible inputs automatically."
        )
    missing_images = [name for name in plan.get("images", {}) if not (root / name).is_file()]
    if missing_images:
        sample = ", ".join(missing_images[:5])
        raise ValueError(
            f"Missing {len(missing_images)} notebook image asset(s): {sample}. "
            "Generate the current case figures or extract their attributed primary rasters "
            "before executing the selected notebook."
        )
    total = sum(archive_size(root / name) for name in (*plan["archives"], *plan.get("images", {})))
    if total > maximum_bytes:
        raise ValueError(
            f"Notebook archives require {total:,} bytes, exceeding "
            f"the explicit {maximum_bytes:,}-byte budget"
        )


def main() -> None:
    """List dependencies by default; validate generated payloads when requested."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Require the selected local payloads")
    parser.add_argument("--max-bytes", type=int, default=DEFAULT_MAX_BYTES)
    parser.add_argument(
        "--notebook", action="append", help="Select an ID, path or problem folder, e.g. 23 or darcy"
    )
    args = parser.parse_args()
    root = case_workspace()
    try:
        paths = select_notebooks(root, args.notebook)
    except ValueError as error:
        parser.error(str(error))
    selected = selected_notebook_ids(root, paths) if args.notebook else None
    dependencies = required_archives(root, selected)
    plan = dependency_plan(root, dependencies, required_images(root, selected))
    plan["notebook_paths"] = [path.relative_to(root / "notebooks").as_posix() for path in paths]
    print(json.dumps(plan, indent=2), flush=True)
    if args.check:
        try:
            validate_archives(root, plan, args.max_bytes)
        except ValueError as error:
            parser.error(str(error))


if __name__ == "__main__":
    main()
